import type { Metadata } from "next";
import { Lora } from "next/font/google";
import Link from "@/components/Link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
import { HeroSection } from "./HeroSection";
import { LyricsToMusicGenerator } from "./LyricsToMusicGenerator";

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});

const PAGE_URL = "/ai-lyrics-to-music-generator";
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://theaimusicgenerator.com";

export const metadata: Metadata = {
  title: { absolute: "Lyrics to Music | AI Music Generator from Lyrics - Turn Your Words into Songs (2026)" },
  description:
    "AI music generator from lyrics: turn your words into songs in seconds. Best AI songwriting assistant for 2026. Suno & ChatGPT lyrics compatible. v6 model captures emotion & semantics.",
  keywords: [
    "AI music generator from lyrics",
    "ai generated music from text",
    "best ai songwriting assistant",
    "suno chatgpt music integration",
    "lyrics to music",
  ],
  openGraph: {
    title: "Lyrics to Music | AI Music Generator from Lyrics - Turn Words into Songs (2026)",
    description:
      "Turn your lyrics into full songs with our v6 AI. Best ai songwriting assistant. ChatGPT & Suno compatible. Royalty-free.",
    url: `${SITE_URL}${PAGE_URL}`,
    siteName: "The AI Music Generator",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/images/home/hero-card-ai-music-generator.webp",
        width: 1200,
        height: 630,
        alt: "AI Music Generator from Lyrics - Turn Your Words into Songs",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Lyrics to Music | AI Music Generator from Lyrics (2026)",
    description: "Turn your words into songs. v6 model. ChatGPT & Suno lyrics compatible. Royalty-free.",
    images: ["/images/home/hero-card-ai-music-generator.webp"],
  },
  alternates: { canonical: `${SITE_URL}${PAGE_URL}` },
};

const FAQ_ITEMS = [
  {
    question: "Can I use ChatGPT lyrics with this generator?",
    answer:
      "Yes! We are fully compatible with lyrics generated by ChatGPT. Simply paste them in to start the v6 music generation process.",
  },
  {
    question: "Does the AI understand the rhyme and meter of my lyrics?",
    answer:
      "Our 2026 model uses advanced NLP to analyze cadence, ensuring the melody aligns with your song's natural flow.",
  },
  {
    question: "What genres work best with lyrics-based generation?",
    answer:
      "From AI generated blues music to contemporary pop, our engine adapts to any genre you specify in the prompt.",
  },
] as const;

function schemaText(s: string): string {
  return s
    .replace(/\u2019/g, "'")
    .replace(/\u2014/g, " - ")
    .replace(/\u2013/g, " - ");
}

function getPageSchema() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "AI Lyrics to Music Generator", item: `${SITE_URL}${PAGE_URL}` },
        ],
      },
      {
        "@type": "HowTo",
        name: "How to Turn Your Lyrics into a Song",
        description:
          "Use The AI Music Generator to convert your lyrics into a full song with melody and production. Paste your lyrics, click Turn Lyrics to Melody, and the v6 model generates music that matches the emotion and flow of your words.",
        step: [
          {
            "@type": "HowToStep",
            position: 1,
            name: "Paste or type your lyrics",
            text: "Enter your lyrics in the generator text area. You can use lyrics from ChatGPT, Suno, or your own writing.",
          },
          {
            "@type": "HowToStep",
            position: 2,
            name: "Optional: set genre and mood",
            text: "Specify genre (e.g. blues, pop, christian) and mood so the v6 model matches BPM and style to your lyrics.",
          },
          {
            "@type": "HowToStep",
            position: 3,
            name: "Click Turn Lyrics to Melody",
            text: "The AI analyzes cadence and emotion, then generates a full song. Download royalty-free for commercial use.",
          },
        ],
        url: `${SITE_URL}${PAGE_URL}`,
      },
      {
        "@type": "FAQPage",
        name: "AI Lyrics to Music Generator - FAQ",
        mainEntity: FAQ_ITEMS.map((item) => ({
          "@type": "Question",
          name: schemaText(item.question),
          acceptedAnswer: {
            "@type": "Answer",
            text: schemaText(item.answer),
          },
        })),
      },
    ],
  };
}

export default function AiLyricsToMusicGeneratorPage() {
  const schema = getPageSchema();

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <main
        className={`${lora.className} min-h-screen`}
        style={{
          background: "linear-gradient(180deg, #f8f4eb 0%, #f2ebe0 30%, #ebe4d8 100%)",
        }}
      >
        <SiteHeader hideLandingLinks mobileNavKind="tools" currentPath={PAGE_URL} />

        {/* H1 for SEO — visible in DOM, styled as page title */}
        <div className="sr-only">
          <h1>AI Music Generator from Lyrics: Turn Your Words into Songs (2026)</h1>
        </div>

        <HeroSection />

        {/* Generator: large textarea + Turn to Melody CTA */}
        <div className="mx-auto max-w-4xl px-4 py-12">
          <LyricsToMusicGenerator />
        </div>

        {/* Emotional Mapping Feature */}
        <section className="border-t border-amber-200/40 bg-white/40 py-14">
          <div className="mx-auto max-w-4xl px-4">
            <h2 className="text-2xl font-semibold text-stone-800 sm:text-3xl">
              Emotional Mapping: From Mood to BPM &amp; Genre
            </h2>
            <p className="mt-3 text-stone-600 leading-relaxed">
              Our v6 model doesn&apos;t just set words to random beats. It reads the emotional tone of your lyrics—melancholy, joyful, or intense—and automatically suggests or applies matching <strong>BPM</strong> and <strong>genre</strong>. Whether your lines call for slow <strong>blues</strong>, uplifting <strong>christian</strong> arrangements, or high-energy pop, the engine adapts so the final track feels true to what you wrote.
            </p>
            <div className="mt-6 overflow-hidden rounded-xl border border-amber-200/50 bg-amber-50/60">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="border-b border-amber-200/60 bg-amber-100/50">
                    <th className="py-3 px-4 font-semibold text-stone-800">Lyrics mood</th>
                    <th className="py-3 px-4 font-semibold text-stone-800">Typical BPM range</th>
                    <th className="py-3 px-4 font-semibold text-stone-800">Example genres</th>
                  </tr>
                </thead>
                <tbody className="text-stone-700">
                  <tr className="border-b border-amber-200/40">
                    <td className="py-2.5 px-4">Melancholy / reflective</td>
                    <td className="py-2.5 px-4">60–80</td>
                    <td className="py-2.5 px-4">Blues, ballad, ambient</td>
                  </tr>
                  <tr className="border-b border-amber-200/40">
                    <td className="py-2.5 px-4">Joyful / upbeat</td>
                    <td className="py-2.5 px-4">100–120</td>
                    <td className="py-2.5 px-4">Pop, folk, christian</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4">Intense / energetic</td>
                    <td className="py-2.5 px-4">120–140+</td>
                    <td className="py-2.5 px-4">Rock, EDM, hip-hop</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* Creator Toolkit */}
        <section className="border-t border-amber-200/40 py-14">
          <div className="mx-auto max-w-4xl px-4">
            <h2 className="text-2xl font-semibold text-stone-800 sm:text-3xl">
              Creator Toolkit: From Lyrics to Video
            </h2>
            <p className="mt-3 text-stone-600">
              Use our tools in sequence for a complete creative pipeline.
            </p>
            <div className="mt-8 grid gap-6 sm:grid-cols-3">
              {[
                {
                  step: "1",
                  title: "AI Lyrics Generator",
                  desc: "Get inspiration or full lyrics from AI. Set mood, structure, and style.",
                  href: "/ai-lyrics-generator",
                },
                {
                  step: "2",
                  title: "AI Lyrics to Music",
                  desc: "Paste your lyrics here. Our v6 model turns them into melody and production.",
                  href: PAGE_URL,
                },
                {
                  step: "3",
                  title: "AI Music Video Generator",
                  desc: "Turn your track into a music video. Cinematic, Anime, or Lo-fi styles.",
                  href: "/ai-music-video-generator",
                },
              ].map(({ step, title, desc, href }) => (
                <Link
                  key={step}
                  href={href}
                  className="block rounded-xl border border-amber-200/50 bg-white/70 p-5 shadow-sm transition hover:border-amber-300/60 hover:shadow-md"
                >
                  <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-amber-200/60 text-sm font-semibold text-amber-900">
                    {step}
                  </span>
                  <h3 className="mt-3 font-semibold text-stone-800">{title}</h3>
                  <p className="mt-1 text-sm text-stone-600">{desc}</p>
                </Link>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section id="faq" className="border-t border-amber-200/40 bg-white/30 py-14">
          <div className="mx-auto max-w-3xl px-4">
            <h2 className="text-2xl font-semibold text-stone-800 sm:text-3xl">FAQ</h2>
            <div className="mt-6 space-y-3">
              {FAQ_ITEMS.map((item) => (
                <details
                  key={item.question}
                  className="rounded-xl border border-amber-200/40 bg-white/70 p-4 shadow-sm"
                >
                  <summary className="cursor-pointer font-semibold text-stone-800">
                    {item.question}
                  </summary>
                  <p className="mt-2 text-sm leading-relaxed text-stone-600">{item.answer}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* Internal links */}
        <section className="border-t border-amber-200/40 py-10">
          <div className="mx-auto max-w-4xl px-4 text-center">
            <p className="text-sm text-stone-600">
              <Link href="/ai-lyrics-generator" className="text-violet-700 underline underline-offset-2 hover:text-violet-800">AI Lyrics Generator</Link>
              {" · "}
              <Link href="/ai-music-generator" className="text-violet-700 underline underline-offset-2 hover:text-violet-800">AI Music Generator</Link>
              {" · "}
              <Link href="/ai-music-video-generator" className="text-violet-700 underline underline-offset-2 hover:text-violet-800">AI Music Video Generator</Link>
              {" · "}
              <Link href="/free-ai-lofi-generator" className="text-violet-700 underline underline-offset-2 hover:text-violet-800">Free AI Lofi Generator</Link>
              {" · "}
              <Link href="/pricing" className="text-violet-700 underline underline-offset-2 hover:text-violet-800">Pricing</Link>
            </p>
            <Link
              href="/ai-music-generator"
              className="mt-6 inline-flex items-center justify-center rounded-full bg-violet-600 px-6 py-3 text-sm font-semibold text-white hover:bg-violet-500"
            >
              Start creating music
            </Link>
          </div>
        </section>

        <SiteFooter />
      </main>
    </>
  );
}
