// app/page.tsx — Home: 10 sections, purple theme, centered, image placeholders
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { getHomeFaqJsonLd } from "./home-faq-ld";
import { HomeFeatureImage, HomeCtaImage } from "../components/HomeFeatureImage";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { HomeSampleTracks } from "../components/HomeSampleTracks";

export const metadata: Metadata = {
  title: "The AI Music Generator for Modern Creators",
  description:
    "Turn text into songs and instrumentals in seconds. Free AI music generator and lyrics tool for creators, filmmakers, and musicians. Royalty-free music from a single prompt.",
};

const sampleTracks = [
  { category: "Full track · Cinematic", title: "Cinematic opener", description: "An epic intro created with our AI music generator for product launches and trailers.", audioSrc: "/audio/sample-cinematic.mp3", coverSrc: "/images/covers/sample-cinematic.jpg" },
  { category: "Instrumental · Lo-fi", title: "Lo-fi focus instrumental", description: "A laid-back instrumental you can recreate in one click using our instrumental AI music tool.", audioSrc: "/audio/sample-lofi.mp3", coverSrc: "/images/covers/sample-lofi.jpg" },
  { category: "Loop · Background", title: "Loop for talking videos", description: "A subtle loop designed for talking-head videos, generated by the same AI music generator engine.", audioSrc: "/audio/sample-loop.mp3", coverSrc: "/images/covers/sample-loop.jpg" },
  { category: "Short clip · Social", title: "15-second social clip", description: "A short, punchy idea you can turn into a full song on the AI music generator page.", audioSrc: "/audio/sample-social.mp3", coverSrc: "/images/covers/sample-social.jpg" },
  { category: "Full track · Documentary", title: "Documentary emotional bed", description: "Gentle piano and strings for storytelling and narrative moments.", audioSrc: "/audio/sample-documentary.mp3", coverSrc: "/images/covers/sample-documentary.jpg" },
  { category: "Short clip · Vlog", title: "Upbeat vlog intro", description: "Bright acoustic energy for channel or episode openers.", audioSrc: "/audio/sample-vlog.mp3", coverSrc: "/images/covers/sample-vlog.jpg" },
  { category: "Instrumental · R&B", title: "Late night R&B groove", description: "Smooth neo-soul vibe for chill or romantic mood.", audioSrc: "/audio/sample-rnb.mp3", coverSrc: "/images/covers/sample-rnb.jpg" },
  { category: "Loop · Ambient", title: "Game menu ambient", description: "Calm, peaceful loop for game menus or app backgrounds.", audioSrc: "/audio/sample-ambient.mp3", coverSrc: "/images/covers/sample-ambient.jpg" },
];

// 功能卡与 CTA 配图（置于 public/images/home/）
const FEATURE_CARD_IMAGES = [
  { src: "/images/home/hero-card-ai-music-generator.jpg", alt: "Producer in home studio with laptop and speakers" },
  { src: "/images/home/hero-card-ai-lyrics-generator.jpg", alt: "Songwriter writing lyrics at desk with notebook and laptop" },
  { src: "/images/home/hero-card-ai-music-tools.jpg", alt: "Content creator with microphone and laptop" },
] as const;

const EXPLORE_IMAGES = [
  { src: "/images/home/explore-instrumental.jpg", alt: "Musician with guitar or keyboard in minimal home studio" },
  { src: "/images/home/explore-loops.jpg", alt: "Person editing video on laptop with headphones" },
  { src: "/images/home/explore-idea-starters.jpg", alt: "Creative person with headphones listening to music" },
] as const;

export default function Home() {
  const homeFaqLd = getHomeFaqJsonLd();
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(homeFaqLd) }}
      />
      <main className="min-h-screen bg-slate-950 text-slate-50">
      {/* 使用统一 SiteHeader：移动端仅图标+汉堡菜单，修复 Sign in 溢出 */}
      <SiteHeader />

      {/* 1) HERO — H1 two lines; three tags (musiccreator style) */}
      <section className="border-b border-slate-900 bg-gradient-to-b from-slate-950 via-slate-950 to-slate-900 min-h-[85vh] flex flex-col justify-center">
        <div className="mx-auto max-w-6xl w-full px-4 py-12 sm:py-16 text-center">
          <div className="mx-auto max-w-3xl space-y-4">
            <h1 className="text-5xl font-semibold tracking-tight text-slate-50 sm:text-6xl md:text-7xl leading-tight">
              <span className="block sm:whitespace-nowrap">The AI Music Generator</span>
              <span className="block">for Modern Creators</span>
            </h1>
            <p className="text-balance text-lg leading-relaxed text-slate-300">
              Turn plain text ideas into ready-to-use songs and instrumentals in seconds with an AI music generator built for real projects.
            </p>
          </div>
          <div className="mt-8 mx-auto max-w-2xl space-y-4">
            <div className="flex flex-col gap-3 rounded-2xl border border-slate-800/90 bg-slate-950/80 p-3 shadow-[0_24px_80px_rgba(0,0,0,0.9)] sm:flex-row sm:items-center">
              <input
                type="text"
                placeholder="Describe the track you want to create with our AI music generator…"
                className="flex-1 rounded-xl border border-slate-800 bg-slate-900/80 px-3 py-2.5 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus-visible:ring-1 focus-visible:ring-violet-400/60"
              />
              <Link href="/ai-music-generator" className="inline-flex w-full items-center justify-center rounded-full bg-violet-500 px-5 py-2.5 text-sm font-semibold text-white shadow-[0_0_28px_rgba(139,92,246,0.5)] transition hover:bg-violet-400 sm:w-auto">
                Generate with AI
              </Link>
            </div>
            <div className="flex flex-wrap items-center justify-center gap-4 sm:gap-6 md:justify-between md:px-4">
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-3 py-1.5 text-sm text-slate-300">
                <span className="text-[10px] font-medium uppercase tracking-wider text-violet-400">Duration</span>
                Up to 8 mins
              </span>
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-3 py-1.5 text-sm text-slate-300">
                <span className="text-[10px] font-medium uppercase tracking-wider text-violet-400">License</span>
                100% Royalty-Free
              </span>
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-3 py-1.5 text-sm text-slate-300">
                <span className="text-[10px] font-medium uppercase tracking-wider text-violet-400">Model</span>
                2026 latest model v6
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* 2) THREE CORE FEATURE CARDS — centered, image placeholders */}
      <section className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-6xl px-4 py-14 text-center">
          <h2 className="mb-4 text-3xl font-semibold text-slate-100">Everything you need in one AI music generator</h2>
          <p className="mb-10 text-base text-slate-400 max-w-2xl mx-auto">One platform for full tracks, lyrics, and focused tools.</p>
          <div className="grid gap-6 md:grid-cols-3 text-left">
            {[
              { title: "AI music generator for full tracks", copy: "Generate complete songs and instrumentals from a single text prompt, ready for videos, games, and podcasts.", href: "/ai-music-generator", label: "Open AI music generator →" },
              { title: "AI lyrics generator for hooks and verses", copy: "Write studio-ready lyrics in seconds, then turn them into songs with the same AI music generator workflow.", href: "/ai-lyrics-generator", label: "Try AI lyrics generator →" },
              { title: "AI music tools for every workflow", copy: "Explore focused AI music tools for instrumentals, loops, and more — all powered by our core AI music generator engine.", href: "/ai-music-tools", label: "Explore AI music tools →" },
            ].map((card, i) => (
              <article key={card.title} className="flex flex-col rounded-2xl border border-slate-800 bg-slate-900/70 p-5">
                <HomeFeatureImage src={FEATURE_CARD_IMAGES[i].src} alt={FEATURE_CARD_IMAGES[i].alt} className="mb-4" />
                <h3 className="mb-2 text-base font-semibold text-slate-50">{card.title}</h3>
                <p className="mb-4 text-sm leading-relaxed text-slate-300">{card.copy}</p>
                <Link href={card.href} className="mt-auto text-sm font-semibold text-violet-300 hover:text-violet-200">{card.label}</Link>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* 3) SAMPLE TRACKS — 2 rows × 4 cols, play on image, no bottom link, one viewport */}
      <section className="border-b border-slate-900 bg-slate-950 min-h-screen flex flex-col">
        <div className="mx-auto max-w-6xl px-4 py-6 md:py-8 text-center flex-1 flex flex-col min-h-0">
          <h2 className="mb-1 text-3xl font-semibold text-slate-100">Hear what our AI music generator sounds like</h2>
          <p className="mb-4 md:mb-5 text-base text-slate-400 max-w-2xl mx-auto">Preview songs, instrumentals, and loops created with our AI music generator across different genres and moods.</p>
          <HomeSampleTracks tracks={sampleTracks} />
        </div>
      </section>

      {/* 4) EXPLORE AI MUSIC MAKER TOOLS — centered */}
      <section className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-6xl px-4 py-14 text-center">
          <h2 className="mb-2 text-3xl font-semibold text-slate-100">Explore AI music maker tools</h2>
          <p className="mb-10 text-base text-slate-400 max-w-2xl mx-auto">Discover focused AI music tools for instrumentals, loops, and songwriting — all built on the same AI music generator.</p>
          <div className="grid gap-6 md:grid-cols-3 text-left">
            {[
              { title: "Instrumental generator", copy: "Turn any idea into a clean instrumental with our AI music generator, ready for background use.", href: "/ai-music-tools#instrumentals", label: "Open instrumental generator" },
              { title: "Loops and background music", copy: "Quickly generate loops for talking-head videos, tutorials, and explainers without digging through stock libraries.", href: "/ai-music-tools#loops", label: "Explore loops tool" },
              { title: "Idea starters", copy: "Random prompts and idea starters when you just want to hear something new from the AI music generator.", href: "/ai-music-generator", label: "Open AI music generator" },
            ].map((card, i) => (
              <article key={card.title} className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
                <HomeFeatureImage src={EXPLORE_IMAGES[i].src} alt={EXPLORE_IMAGES[i].alt} className="mb-4" />
                <h3 className="mb-2 text-base font-semibold text-slate-50">{card.title}</h3>
                <p className="mb-3 text-sm text-slate-300">{card.copy}</p>
                <Link href={card.href} className="text-sm text-violet-300 hover:underline">{card.label}</Link>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* 5) THE SPARK — centered */}
      <section className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-4xl px-4 py-14 text-center">
          <h2 className="mb-6 text-3xl font-semibold text-slate-100">The spark for your sound</h2>
          <div className="grid md:grid-cols-2 gap-8 items-start">
            <div className="space-y-3 text-left">
              <p className="text-base leading-relaxed text-slate-300">
                Whether you are a producer, content creator, or founder, our AI music generator gives you the first spark — a finished track, an idea for a hook, or an instrumental you can build on.
              </p>
              <p className="text-base leading-relaxed text-slate-300">
                Start with a text prompt, a mood, or an existing idea, and let the AI music generator handle the heavy lifting so you can stay focused on the story you want to tell.
              </p>
            </div>
            <div className="relative aspect-video w-full rounded-xl overflow-hidden bg-slate-800/50">
              <Image src="/images/home/spark-creators.jpg" alt="Diverse creators in a creative space" fill className="object-cover" sizes="(max-width: 768px) 100vw, 50vw" unoptimized />
            </div>
          </div>
        </div>
      </section>

      {/* 6) HOW IT WORKS — centered */}
      <section className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-6xl px-4 py-14 text-center">
          <h2 className="mb-10 text-3xl font-semibold text-slate-100">How our AI music generator works</h2>
          <div className="grid gap-6 md:grid-cols-3 text-left">
            {[
              { step: "1. Describe your track", text: "Tell the AI music generator what you need: genre, mood, tempo, and whether you want full vocals or an instrumental.", img: "/images/home/how-1-describe.jpg", alt: "Person typing on laptop, thinking" },
              { step: "2. Let AI compose", text: "We process your prompt, queue your request, and our AI music generator builds one or more unique tracks for you.", img: "/images/home/how-2-ai-compose.jpg", alt: "Hands on keyboard with sound waves" },
              { step: "3. Preview, refine, and export", text: "Listen inside the browser, tweak your prompt, then export audio for your videos, games, or podcasts.", img: "/images/home/how-3-export.jpg", alt: "Creator with headphones exporting" },
            ].map((item) => (
              <div key={item.step} className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
                <div className="relative aspect-video mb-4 rounded-xl overflow-hidden bg-slate-800/50">
                  <Image src={item.img} alt={item.alt} fill className="object-cover" sizes="(max-width: 768px) 100vw, 33vw" unoptimized />
                </div>
                <h3 className="mb-1 text-base font-semibold text-slate-50">{item.step}</h3>
                <p className="text-sm text-slate-300">{item.text}</p>
              </div>
            ))}
          </div>
          <p className="mt-6 text-sm text-slate-400">
            Ready to try it? <Link href="/ai-music-generator" className="text-violet-300 hover:underline">Open the AI music generator</Link>.
          </p>
        </div>
      </section>

      {/* 7) USE CASES — centered */}
      <section id="use-cases" className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-6xl px-4 py-14 text-center">
          <h2 className="mb-10 text-3xl font-semibold text-slate-100">How creators use our AI music generator</h2>
          <div className="mb-8 max-w-3xl mx-auto relative aspect-[2/1] rounded-xl overflow-hidden bg-slate-800/50">
            <Image src="/images/home/use-cases-creators.jpg" alt="Content studio with creators and equipment" fill className="object-cover" sizes="(max-width: 768px) 100vw, 896px" unoptimized />
          </div>
          <div className="grid gap-6 sm:grid-cols-2 text-left">
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">YouTube & talking-head videos</h3>
              <p className="text-sm text-slate-300">Record your video, drop a line like &quot;warm, friendly background music for a productivity vlog&quot; into the <Link href="/ai-music-generator" className="text-violet-300 hover:underline">AI music generator</Link>, and get a track that sits behind your voice.</p>
            </article>
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">Short-form social clips</h3>
              <p className="text-sm text-slate-300">When you need five versions of a 10-second sound for Reels or Shorts, paste the same prompt into our AI music generator, tweak the energy level, and test which one keeps viewers watching longer.</p>
            </article>
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">Indie game levels</h3>
              <p className="text-sm text-slate-300">Describe the feeling — &quot;slow build, a bit tense&quot; — and let the AI music generator create an <Link href="/ai-music-tools#instrumentals" className="text-violet-300 hover:underline">instrumental bed</Link>. Regenerate until the music feels right.</p>
            </article>
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">Podcasts and narration</h3>
              <p className="text-sm text-slate-300">Hosts type in the topic and mood; the AI music generator builds a unique intro and a softer mid-roll version. Consistent but not repetitive.</p>
            </article>
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">Startup launch pages</h3>
              <p className="text-sm text-slate-300">Founders drop a one-sentence product description into the AI music generator to get a launch song that matches their brand.</p>
            </article>
            <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <h3 className="mb-1 text-base font-semibold text-slate-50">Songwriters testing ideas</h3>
              <p className="text-sm text-slate-300">Songwriters paste a <Link href="/ai-lyrics-generator" className="text-violet-300 hover:underline">rough lyric</Link>, choose &quot;simple piano&quot; in the generator, and listen to how the melody might feel before booking studio time.</p>
            </article>
          </div>
        </div>
      </section>

      {/* 8) WHO USES — centered */}
      <section className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-4xl px-4 py-14 text-center">
          <h2 className="mb-4 text-3xl font-semibold text-slate-100">Who our <Link href="/ai-music-generator" className="text-violet-300 hover:underline">AI song maker</Link> is built for</h2>
          <p className="mb-6 text-base text-slate-300">Our AI song maker sits on top of the same AI music generator engine, but it adapts to very different workflows.</p>
          <div className="relative aspect-[2.2/1] mb-8 max-w-3xl mx-auto rounded-xl overflow-hidden bg-slate-800/50">
            <Image src="/images/home/who-uses-community.jpg" alt="Creative community in shared workspace" fill className="object-cover" sizes="(max-width: 768px) 100vw, 896px" unoptimized />
          </div>
          <ul className="list-disc space-y-1 pl-5 text-left text-base text-slate-300 max-w-xl mx-auto">
            <li>YouTube creators who want background music that fits their voice and pacing.</li>
            <li>Short-form editors who need fresh, punchy clips every day without chasing rights.</li>
            <li>Indie game developers looking for instrumentals that evolve with each level.</li>
            <li>Podcast hosts who want distinct intros and transitions without hiring a composer.</li>
            <li>Startup teams launching new products and wanting a sound that matches their brand.</li>
            <li>Songwriters and producers using the AI song maker as a fast sketchpad for ideas.</li>
          </ul>
          <p className="mt-6 text-sm text-slate-400">See more in our <Link href="#use-cases" className="text-violet-300 hover:underline">AI music generator use cases</Link>.</p>
        </div>
      </section>

      {/* 9) COPYRIGHT — centered */}
      <section id="copyright" className="border-b border-slate-900 bg-slate-950">
        <div className="mx-auto max-w-6xl px-4 py-14 text-center">
          <h2 className="mb-4 text-3xl font-semibold text-slate-100">How copyright works with our AI music generator</h2>
          <p className="mb-6 text-base text-slate-400 max-w-2xl mx-auto">Clear licensing so you can use your tracks everywhere.</p>
          <div className="grid md:grid-cols-2 gap-8 items-center text-left">
            <div className="space-y-3 text-base text-slate-300 order-2 md:order-1">
              <p>Tracks you create with our AI music generator come with a clear license for online use in videos, streams, podcasts, and more.</p>
              <p>We design our AI music generator to avoid copying existing songs, but we cannot provide legal advice. For high-stakes campaigns, we recommend consulting your own counsel.</p>
              <p><Link href="/license" className="text-violet-300 hover:underline">Read full licensing details</Link>.</p>
            </div>
            <div className="order-1 md:order-2 relative aspect-video w-full max-w-xl mx-auto rounded-xl overflow-hidden bg-slate-800/50">
              <Image src="/images/home/copyright-license.jpg" alt="Professional reviewing license document" fill className="object-cover" sizes="(max-width: 768px) 100vw, 50vw" unoptimized />
            </div>
          </div>
        </div>
      </section>

      {/* 10) FAQ — centered */}
      <section className="bg-slate-950">
        <div className="mx-auto max-w-3xl px-4 py-14 text-center">
          <h2 className="mb-6 text-3xl font-semibold text-slate-100">AI music generator FAQ</h2>
          <div className="space-y-3 text-left">
            <details className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <summary className="cursor-pointer text-base font-semibold text-slate-50">What can I create with your AI music generator?</summary>
              <p className="mt-2 text-sm text-slate-300">You can generate full songs, short hooks, lyrics, or pure instrumentals — all from text prompts.</p>
            </details>
            <details className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <summary className="cursor-pointer text-base font-semibold text-slate-50">Do I own the music I create?</summary>
              <p className="mt-2 text-sm text-slate-300">You get a broad license. For details, see our <Link href="#copyright" className="text-violet-300 hover:underline">copyright and licensing section</Link>.</p>
            </details>
            <details className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <summary className="cursor-pointer text-base font-semibold text-slate-50">Can I use AI-generated music on YouTube or TikTok?</summary>
              <p className="mt-2 text-sm text-slate-300">Yes. We recommend testing on non-critical videos first and reviewing our licensing terms.</p>
            </details>
            <details className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <summary className="cursor-pointer text-base font-semibold text-slate-50">Do I need music production experience?</summary>
              <p className="mt-2 text-sm text-slate-300">Not at all. If you can describe how you want your song to feel, the AI music generator can turn that into audio.</p>
            </details>
            <details className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4">
              <summary className="cursor-pointer text-base font-semibold text-slate-50">Can I start with lyrics first?</summary>
              <p className="mt-2 text-sm text-slate-300">Yes. You can use our <Link href="/ai-lyrics-generator" className="text-violet-300 hover:underline">AI lyrics generator</Link> and then turn them into songs with the same <Link href="/ai-music-generator" className="text-violet-300 hover:underline">AI music generator</Link> workflow.</p>
            </details>
          </div>
        </div>
      </section>

      {/* CTA block — background image + overlay；移动端防溢出：按钮竖排、内边距与宽高比适配 */}
      <section className="border-b border-slate-900 bg-slate-950 overflow-hidden">
        <div className="mx-auto max-w-6xl px-3 sm:px-4 py-10 sm:py-14 text-center">
          <div className="relative rounded-2xl sm:rounded-3xl border border-slate-800 bg-slate-900/80 overflow-hidden aspect-[4/3] sm:aspect-[3/1] min-h-[260px] sm:min-h-[280px] w-full max-w-full">
            <HomeCtaImage src="/images/home/cta-ready-to-create.jpg" alt="Creator ready to make music">
              <div className="absolute inset-0 z-10 bg-slate-950/60 flex flex-col items-center justify-center gap-3 sm:gap-4 p-4 sm:p-6">
                <h2 className="text-xl sm:text-2xl md:text-3xl font-semibold text-slate-50 px-1">Ready to create your own unique music?</h2>
                <p className="text-sm sm:text-base text-slate-300 max-w-xl px-1">Join thousands of creators who use our AI music generator.</p>
                <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center gap-2 sm:gap-3 mt-1 w-full max-w-xs sm:max-w-none sm:w-auto">
                  <Link href="/ai-music-generator" className="inline-flex items-center justify-center rounded-full bg-violet-500 px-5 sm:px-6 py-2.5 sm:py-3 text-sm sm:text-base font-semibold text-white shadow-[0_0_28px_rgba(139,92,246,0.5)] transition hover:bg-violet-400">Create Music Now</Link>
                  <Link href="/pricing" className="inline-flex items-center justify-center rounded-full border border-slate-600 px-5 sm:px-6 py-2.5 sm:py-3 text-sm sm:text-base font-medium text-slate-200 hover:border-violet-500/50 hover:text-violet-200">View Pricing</Link>
                </div>
              </div>
            </HomeCtaImage>
          </div>
        </div>
      </section>

      {/* Footer — 使用统一 SiteFooter，避免 Legal 链接在多处重复且不一致 */}
      <SiteFooter />
    </main>
    </>
  );
}
