/**
 * 按域名分支的站点文案配置。
 * - 服务端：通过 headers().get("host") 判断当前域名，返回对应文案。
 * - 静态导出（Cloudflare Pages）：无请求头，用 NEXT_PUBLIC_SITE_URL 解析出的 host 匹配。
 * 新增域名：在 BRAND_BY_HOST 加一项，覆盖需要修改的字段即可。
 */

/** 首页各区块全量文案 */
export type HomeCopy = {
  heroSubtitle: string;
  sampleTrackDescriptions: readonly string[];
  section2Heading: string;
  section2Subtitle: string;
  section2Cards: readonly { title: string; copy: string; href: string; label: string }[];
  section3Heading: string;
  section3Subtitle: string;
  section4Heading: string;
  section4Subtitle: string;
  section4Cards: readonly { title: string; copy: string; href: string; label: string }[];
  section5Heading: string;
  section5Body1: string;
  section5Body2: string;
  section6Heading: string;
  section6Steps: readonly { step: string; text: string; img: string; alt: string }[];
  section6FooterCta: string;
  section7Heading: string;
  /** 若存在，section8 标题里的链接词 */
  section8HeadingLinkText?: string;
  section8HeadingLinkHref?: string;
  /** 不带链接时的完整 section8 标题 */
  section8Heading: string;
  section8Subtitle: string;
  section8ListItems: readonly string[];
  section9Heading: string;
  section9Body1: string;
  section9Body2: string;
  section10Heading: string;
  ctaHeading: string;
  ctaSubtitle: string;
};

export type SiteBrandConfig = {
  /** 站点根 URL，用于 metadataBase、sitemap、robots */
  siteUrl: string;
  /** 完整站名，用于 title、og:site_name、H1 等 */
  siteName: string;
  /** 短名/展示用，如 "AI Music Factory" */
  shortName: string;
  /** 首页 H1 第二行 */
  tagline: string;
  /** 版权行显示的站点名 */
  copyrightName: string;
  /** title 模板 */
  titleTemplate: string;
  /** 默认 title */
  defaultTitle: string;
  /** 默认 description */
  defaultDescription: string;
  /** og:image alt */
  ogImageAlt: string;
  /** 工具的行文称呼，用于 body 中 inline 品牌提及 */
  toolName: string;
  /** 首页各区块文案 */
  home: HomeCopy;
};

// ─────────────────────────────────────────────────────────────────────────────
// TAMG — The AI Music Generator（默认）
// ─────────────────────────────────────────────────────────────────────────────

const TAMG_HOME_COPY: HomeCopy = {
  heroSubtitle:
    "Turn plain text ideas into ready-to-use songs and instrumentals in seconds with an AI music generator built for real projects.",
  sampleTrackDescriptions: [
    "An epic intro created with our AI music generator for product launches and trailers.",
    "A laid-back instrumental you can recreate in one click using our instrumental AI music tool.",
    "A subtle loop designed for talking-head videos, generated by the same AI music generator engine.",
    "A short, punchy idea you can turn into a full song on the AI music generator page.",
    "Gentle piano and strings for storytelling and narrative moments.",
    "Bright acoustic energy for channel or episode openers.",
    "Smooth neo-soul vibe for chill or romantic mood.",
    "Calm, peaceful loop for game menus or app backgrounds.",
  ],
  section2Heading: "Everything you need in one AI music generator",
  section2Subtitle: "One platform for full tracks, lyrics, and focused tools.",
  section2Cards: [
    { title: "AI music generator for full tracks", copy: "Generate complete songs and instrumentals from a single text prompt, ready for videos, games, and podcasts.", href: "/ai-music-generator", label: "Open AI music generator →" },
    { title: "AI lyrics generator for hooks and verses", copy: "Write studio-ready lyrics in seconds, then turn them into songs with the same AI music generator workflow.", href: "/ai-lyrics-generator", label: "Try AI lyrics generator →" },
    { title: "AI music tools for every workflow", copy: "Explore focused AI music tools for instrumentals, loops, and more — all powered by our core AI music generator engine.", href: "/ai-music-tools", label: "Explore AI music tools →" },
  ],
  section3Heading: "Hear what our AI music generator sounds like",
  section3Subtitle: "Preview songs, instrumentals, and loops created with our AI music generator across different genres and moods.",
  section4Heading: "Explore AI music maker tools",
  section4Subtitle: "Discover focused AI music tools for instrumentals, loops, and songwriting — all built on the same AI music generator.",
  section4Cards: [
    { title: "Instrumental generator", copy: "Turn any idea into a clean instrumental with our AI music generator, ready for background use.", href: "/ai-music-tools#instrumentals", label: "Open instrumental generator" },
    { title: "Loops and background music", copy: "Quickly generate loops for talking-head videos, tutorials, and explainers without digging through stock libraries.", href: "/ai-music-tools#loops", label: "Explore loops tool" },
    { title: "Idea starters", copy: "Random prompts and idea starters when you just want to hear something new from the AI music generator.", href: "/ai-music-generator", label: "Open AI music generator" },
  ],
  section5Heading: "The spark for your sound",
  section5Body1: "Whether you are a producer, content creator, or founder, our AI music generator gives you the first spark — a finished track, an idea for a hook, or an instrumental you can build on.",
  section5Body2: "Start with a text prompt, a mood, or an existing idea, and let the AI music generator handle the heavy lifting so you can stay focused on the story you want to tell.",
  section6Heading: "How our AI music generator works",
  section6Steps: [
    { step: "1. Describe your track", text: "Tell the AI music generator what you need: genre, mood, tempo, and whether you want full vocals or an instrumental.", img: "/images/home/how-1-describe.webp", alt: "Person typing on laptop, thinking" },
    { step: "2. Let AI compose", text: "We process your prompt, queue your request, and our AI music generator builds one or more unique tracks for you.", img: "/images/home/how-2-ai-compose.webp", alt: "Hands on keyboard with sound waves" },
    { step: "3. Preview, refine, and export", text: "Listen inside the browser, tweak your prompt, then export audio for your videos, games, or podcasts.", img: "/images/home/how-3-export.webp", alt: "Creator with headphones exporting" },
  ],
  section6FooterCta: "Open the AI music generator",
  section7Heading: "How creators use our AI music generator",
  section8HeadingLinkText: "AI song maker",
  section8HeadingLinkHref: "/ai-music-generator",
  section8Heading: "Who our AI song maker is built for",
  section8Subtitle: "Our AI song maker sits on top of the same AI music generator engine, but it adapts to very different workflows.",
  section8ListItems: [
    "YouTube creators who want background music that fits their voice and pacing.",
    "Short-form editors who need fresh, punchy clips every day without chasing rights.",
    "Indie game developers looking for instrumentals that evolve with each level.",
    "Podcast hosts who want distinct intros and transitions without hiring a composer.",
    "Startup teams launching new products and wanting a sound that matches their brand.",
    "Songwriters and producers using the AI song maker as a fast sketchpad for ideas.",
  ],
  section9Heading: "How copyright works with our AI music generator",
  section9Body1: "Tracks you create with our AI music generator come with a clear license for online use in videos, streams, podcasts, and more.",
  section9Body2: "We design our AI music generator to avoid copying existing songs, but we cannot provide legal advice. For high-stakes campaigns, we recommend consulting your own counsel.",
  section10Heading: "AI music generator FAQ",
  ctaHeading: "Ready to create your own unique music?",
  ctaSubtitle: "Join thousands of creators who use our AI music generator.",
};

// ─────────────────────────────────────────────────────────────────────────────
// AI Music Factory — 面向内容创作者的批量 AI 音乐生成平台
// SEO focus: batch AI music, bulk music generator, content creator music, AI music factory
// GEO focus: YouTubers, TikTok creators, podcasters, short-form video editors
// ─────────────────────────────────────────────────────────────────────────────

const AMF_HOME_COPY: HomeCopy = {
  heroSubtitle:
    "Describe your content. AI Music Factory produces royalty-free songs, instrumentals, and loops in seconds—ready for your next video, podcast, or social clip.",
  sampleTrackDescriptions: [
    "An epic cinematic intro produced by AI Music Factory—ready for product launches and trailers.",
    "A laid-back lo-fi instrumental generated in one click with AI Music Factory.",
    "A subtle background loop for talking-head videos, produced on demand by AI Music Factory.",
    "A short, punchy social clip—use AI Music Factory to batch-generate variations for Reels and Shorts.",
    "Gentle piano and strings for storytelling and narrative moments.",
    "Bright acoustic energy for channel or episode openers.",
    "Smooth neo-soul vibe for chill or romantic content.",
    "Calm, peaceful ambient loop for game menus or app backgrounds.",
  ],
  section2Heading: "Everything your content pipeline needs, in one place",
  section2Subtitle: "Full tracks, lyrics, and audio tools—built to keep up with your upload schedule.",
  section2Cards: [
    { title: "Batch AI music generation", copy: "Generate songs and instrumentals from text prompts. Build a royalty-free music library that keeps pace with your content calendar.", href: "/ai-music-generator", label: "Start generating music →" },
    { title: "AI lyrics for every style", copy: "Write hooks and full verses in seconds. Turn them into complete tracks with the same AI Music Factory workflow—no music background needed.", href: "/ai-lyrics-generator", label: "Try AI lyrics →" },
    { title: "Audio tools for content creators", copy: "Instrumentals, loops, and background music—produced on demand by AI Music Factory for YouTube, TikTok, podcasts, and beyond.", href: "/ai-music-tools", label: "Explore audio tools →" },
  ],
  section3Heading: "Hear what AI Music Factory sounds like",
  section3Subtitle: "Preview songs, instrumentals, and loops across genres—every track is royalty-free and ready to publish.",
  section4Heading: "Explore the AI Music Factory toolkit",
  section4Subtitle: "Production-ready audio tools for content creators. Generate exactly what your channel needs, on demand.",
  section4Cards: [
    { title: "Instrumental generator", copy: "Turn any idea into a clean instrumental. Perfect for background use in videos, tutorials, and live streams.", href: "/ai-music-tools#instrumentals", label: "Open instrumental generator" },
    { title: "Loops and background music", copy: "Quickly generate loops for talking-head videos and explainers—no stock library or composer needed.", href: "/ai-music-tools#loops", label: "Explore loops tool" },
    { title: "Batch music for social content", copy: "Describe the vibe and generate multiple variations. Find the sound that drives engagement on Reels, Shorts, and TikTok.", href: "/ai-music-generator", label: "Open AI Music Factory" },
  ],
  section5Heading: "Your content deserves original music",
  section5Body1:
    "Whether you publish daily or weekly, AI Music Factory keeps your audio library stocked. Describe the vibe, genre, and mood—get a finished track in seconds.",
  section5Body2:
    "Stop searching stock libraries. AI Music Factory generates unique, royalty-free music matched to your content—on demand, at any scale.",
  section6Heading: "How AI Music Factory works",
  section6Steps: [
    { step: "1. Describe your content", text: "Tell AI Music Factory the genre, mood, and energy level. Add lyrics or keep it instrumental—your call.", img: "/images/home/how-1-describe.webp", alt: "Person typing on laptop, thinking" },
    { step: "2. AI generates your tracks", text: "AI Music Factory processes your prompt and builds unique audio in seconds. Generate one track or queue a batch for your content calendar.", img: "/images/home/how-2-ai-compose.webp", alt: "Hands on keyboard with sound waves" },
    { step: "3. Export and publish", text: "Download royalty-free audio ready for YouTube, TikTok, podcasts, or any platform. No copyright claims, no licensing headaches.", img: "/images/home/how-3-export.webp", alt: "Creator with headphones exporting" },
  ],
  section6FooterCta: "Open AI Music Factory",
  section7Heading: "How content creators use AI Music Factory",
  section8Heading: "Who AI Music Factory is built for",
  section8Subtitle: "Built for creators who ship content fast and need music that keeps up.",
  section8ListItems: [
    "YouTube creators who need background music that fits their voice and pacing—generated in seconds.",
    "Short-form editors who need fresh, royalty-free clips every day for Reels, Shorts, and TikTok.",
    "Indie game developers looking for instrumentals that evolve with each level.",
    "Podcast hosts who want distinct intros and transitions without hiring a composer.",
    "Startup teams launching products and wanting a sound that matches their brand.",
    "Songwriters using AI Music Factory as a fast sketchpad to hear ideas before booking studio time.",
  ],
  section9Heading: "Copyright and licensing with AI Music Factory",
  section9Body1:
    "Every track you produce with AI Music Factory comes with a clear royalty-free license—ready for videos, streams, podcasts, and commercial use.",
  section9Body2:
    "AI Music Factory generates original music, not copies. For high-stakes campaigns, review our full licensing terms or consult your own counsel.",
  section10Heading: "AI Music Factory FAQ",
  ctaHeading: "Ready to build your music library?",
  ctaSubtitle: "Join thousands of content creators who use AI Music Factory to fuel their upload schedules.",
};

// ─────────────────────────────────────────────────────────────────────────────
// Default config (TAMG)
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_SITE_URL =
  (typeof process !== "undefined" && process.env.NEXT_PUBLIC_SITE_URL) ||
  "https://theaimusicgenerator.com";

const DEFAULT_CONFIG: SiteBrandConfig = {
  siteUrl: DEFAULT_SITE_URL,
  siteName: "The AI Music Generator",
  shortName: "The AI Music Generator",
  tagline: "for Modern Creators",
  copyrightName: "TheAIMusicGenerator.com",
  titleTemplate: "%s | The AI Music Generator",
  defaultTitle: "The free AI Music Generator for Creators | Royalty-Free",
  defaultDescription:
    "Turn text into songs and instrumentals in seconds. Free AI music generator and lyrics tool for creators, filmmakers & YouTubers. No copyright strikes—try free.",
  ogImageAlt: "The AI Music Generator – Create royalty-free music with AI",
  toolName: "AI music generator",
  home: TAMG_HOME_COPY,
};

// ─────────────────────────────────────────────────────────────────────────────
// Host → config overrides table
// ─────────────────────────────────────────────────────────────────────────────

const AMF_BRAND: Partial<SiteBrandConfig> = {
  siteUrl: "https://aimusicfactory.com",
  siteName: "AI Music Factory",
  shortName: "AI Music Factory",
  tagline: "Batch AI Music for Content Creators",
  copyrightName: "AIMusicFactory.com",
  titleTemplate: "%s | AI Music Factory",
  defaultTitle: "AI Music Factory – Batch AI Music Generator for Content Creators",
  defaultDescription:
    "Generate royalty-free songs, instrumentals, and lyrics in bulk with AI Music Factory. The batch AI music generator built for YouTubers, podcasters, and digital creators. Try free.",
  ogImageAlt: "AI Music Factory – Batch AI Music Generator for Content Creators",
  toolName: "AI Music Factory",
  home: AMF_HOME_COPY,
};

/** 按 host（不含端口，小写）匹配的配置表；新增域名在此添加 */
const BRAND_BY_HOST: Record<string, Partial<SiteBrandConfig>> = {
  "theaimusicgenerator.com": {},
  "www.theaimusicgenerator.com": {},
  "aimusicfactory.com": AMF_BRAND,
  "www.aimusicfactory.com": { ...AMF_BRAND, siteUrl: "https://aimusicfactory.com" },
};

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function normalizeHost(host: string | null | undefined): string | null {
  if (!host || typeof host !== "string") return null;
  return host.split(":")[0].toLowerCase();
}

/**
 * 根据当前 host 返回站点文案。
 * - 服务端：传入 headers().get("host")。
 * - 静态构建：传入 null，内部用 NEXT_PUBLIC_SITE_URL 的 host 匹配。
 */
export function getSiteConfig(host: string | null | undefined): SiteBrandConfig {
  const effectiveHost =
    normalizeHost(host) ||
    (typeof process !== "undefined" && process.env.NEXT_PUBLIC_SITE_URL
      ? normalizeHost(new URL(process.env.NEXT_PUBLIC_SITE_URL).host)
      : null) ||
    "theaimusicgenerator.com";

  const overrides = BRAND_BY_HOST[effectiveHost];
  const baseUrl =
    overrides?.siteUrl ||
    (effectiveHost ? `https://${effectiveHost}` : DEFAULT_SITE_URL);
  const base = { ...DEFAULT_CONFIG, siteUrl: baseUrl };

  if (!overrides) return base;
  return { ...base, ...overrides };
}

/**
 * 服务端用：从请求头取 host 并返回站点配置。
 * 静态导出时无 headers，会退化为用 NEXT_PUBLIC_SITE_URL 的 host。
 */
export async function getServerSiteConfig(): Promise<SiteBrandConfig> {
  try {
    const { headers } = await import("next/headers");
    const h = await headers();
    const host = h.get("host");
    return getSiteConfig(host);
  } catch {
    return getSiteConfig(null);
  }
}
