/**
 * 按域名分支的站点文案配置。
 * - 服务端：通过 headers().get("host") 判断当前域名，返回对应文案。
 * - 静态导出（Cloudflare Pages）：无请求头，用 NEXT_PUBLIC_SITE_URL 解析出的 host 匹配。
 * 新增域名：在 BRAND_BY_HOST 加一项，覆盖需要修改的字段即可。
 */

/** 首页各区块全量文案 */
export type HomeCopy = {
  heroSubtitle: string;
  sampleTrackDescriptions: readonly string[];
  section2Heading: string;
  section2Subtitle: string;
  section2Cards: readonly { title: string; copy: string; href: string; label: string }[];
  section3Heading: string;
  section3Subtitle: string;
  section4Heading: string;
  section4Subtitle: string;
  section4Cards: readonly { title: string; copy: string; href: string; label: string }[];
  section5Heading: string;
  section5Body1: string;
  section5Body2: string;
  section6Heading: string;
  section6Steps: readonly { step: string; text: string; img: string; alt: string }[];
  section6FooterCta: string;
  section7Heading: string;
  /** 若存在，section8 标题里的链接词 */
  section8HeadingLinkText?: string;
  section8HeadingLinkHref?: string;
  /** 不带链接时的完整 section8 标题 */
  section8Heading: string;
  section8Subtitle: string;
  section8ListItems: readonly string[];
  section9Heading: string;
  section9Body1: string;
  section9Body2: string;
  section10Heading: string;
  /** FAQ 条目，用于页面渲染与 JSON-LD FAQPage schema */
  faqItems: readonly { question: string; answer: string }[];
  ctaHeading: string;
  ctaSubtitle: string;
};

/** 子页面元数据覆盖，key = 路由路径（如 "/ai-music-generator"） */
export type PageMeta = { title: string; description: string };

export type SiteBrandConfig = {
  /** 站点根 URL，用于 metadataBase、sitemap、robots */
  siteUrl: string;
  /** 完整站名，用于 title、og:site_name、H1 等 */
  siteName: string;
  /** 短名/展示用，如 "AI Music Factory" */
  shortName: string;
  /** 首页 H1 第二行 */
  tagline: string;
  /** 版权行显示的站点名 */
  copyrightName: string;
  /** title 模板 */
  titleTemplate: string;
  /** 默认 title */
  defaultTitle: string;
  /** 默认 description */
  defaultDescription: string;
  /** og:image alt */
  ogImageAlt: string;
  /** 工具的行文称呼，用于 body 中 inline 品牌提及 */
  toolName: string;
  /** 首页各区块文案 */
  home: HomeCopy;
  /** 子页面元数据覆盖表（按路由路径）；未覆盖的页面用页面自身的默认值 */
  pagesMeta?: Partial<Record<string, PageMeta>>;
};

// ─────────────────────────────────────────────────────────────────────────────
// TAMG — The AI Music Generator（默认）
// ─────────────────────────────────────────────────────────────────────────────

const TAMG_HOME_COPY: HomeCopy = {
  heroSubtitle:
    "Turn plain text ideas into ready-to-use songs and instrumentals in seconds with an AI music generator built for real projects.",
  sampleTrackDescriptions: [
    "An epic intro created with our AI music generator for product launches and trailers.",
    "A laid-back instrumental you can recreate in one click using our instrumental AI music tool.",
    "A subtle loop designed for talking-head videos, generated by the same AI music generator engine.",
    "A short, punchy idea you can turn into a full song on the AI music generator page.",
    "Gentle piano and strings for storytelling and narrative moments.",
    "Bright acoustic energy for channel or episode openers.",
    "Smooth neo-soul vibe for chill or romantic mood.",
    "Calm, peaceful loop for game menus or app backgrounds.",
  ],
  section2Heading: "Everything you need in one AI music generator",
  section2Subtitle: "One platform for full tracks, lyrics, and focused tools.",
  section2Cards: [
    { title: "AI music generator for full tracks", copy: "Generate complete songs and instrumentals from a single text prompt, ready for videos, games, and podcasts.", href: "/ai-music-generator", label: "Open AI music generator →" },
    { title: "AI lyrics generator for hooks and verses", copy: "Write studio-ready lyrics in seconds, then turn them into songs with the same AI music generator workflow.", href: "/ai-lyrics-generator", label: "Try AI lyrics generator →" },
    { title: "AI music tools for every workflow", copy: "Explore focused AI music tools for instrumentals, loops, and more — all powered by our core AI music generator engine.", href: "/ai-music-tools", label: "Explore AI music tools →" },
  ],
  section3Heading: "Hear what our AI music generator sounds like",
  section3Subtitle: "Preview songs, instrumentals, and loops created with our AI music generator across different genres and moods.",
  section4Heading: "Explore AI music maker tools",
  section4Subtitle: "Discover focused AI music tools for instrumentals, loops, and songwriting — all built on the same AI music generator.",
  section4Cards: [
    { title: "Instrumental generator", copy: "Turn any idea into a clean instrumental with our AI music generator, ready for background use.", href: "/ai-music-tools#instrumentals", label: "Open instrumental generator" },
    { title: "Loops and background music", copy: "Quickly generate loops for talking-head videos, tutorials, and explainers without digging through stock libraries.", href: "/ai-music-tools#loops", label: "Explore loops tool" },
    { title: "Idea starters", copy: "Random prompts and idea starters when you just want to hear something new from the AI music generator.", href: "/ai-music-generator", label: "Open AI music generator" },
  ],
  section5Heading: "The spark for your sound",
  section5Body1: "Whether you are a producer, content creator, or founder, our AI music generator gives you the first spark — a finished track, an idea for a hook, or an instrumental you can build on.",
  section5Body2: "Start with a text prompt, a mood, or an existing idea, and let the AI music generator handle the heavy lifting so you can stay focused on the story you want to tell.",
  section6Heading: "How our AI music generator works",
  section6Steps: [
    { step: "1. Describe your track", text: "Tell the AI music generator what you need: genre, mood, tempo, and whether you want full vocals or an instrumental.", img: "/images/home/how-1-describe.webp", alt: "Person typing on laptop, thinking" },
    { step: "2. Let AI compose", text: "We process your prompt, queue your request, and our AI music generator builds one or more unique tracks for you.", img: "/images/home/how-2-ai-compose.webp", alt: "Hands on keyboard with sound waves" },
    { step: "3. Preview, refine, and export", text: "Listen inside the browser, tweak your prompt, then export audio for your videos, games, or podcasts.", img: "/images/home/how-3-export.webp", alt: "Creator with headphones exporting" },
  ],
  section6FooterCta: "Open the AI music generator",
  section7Heading: "How creators use our AI music generator",
  section8HeadingLinkText: "AI song maker",
  section8HeadingLinkHref: "/ai-music-generator",
  section8Heading: "Who our AI song maker is built for",
  section8Subtitle: "Our AI song maker sits on top of the same AI music generator engine, but it adapts to very different workflows.",
  section8ListItems: [
    "YouTube creators who want background music that fits their voice and pacing.",
    "Short-form editors who need fresh, punchy clips every day without chasing rights.",
    "Indie game developers looking for instrumentals that evolve with each level.",
    "Podcast hosts who want distinct intros and transitions without hiring a composer.",
    "Startup teams launching new products and wanting a sound that matches their brand.",
    "Songwriters and producers using the AI song maker as a fast sketchpad for ideas.",
  ],
  section9Heading: "How copyright works with our AI music generator",
  section9Body1: "Tracks you create with our AI music generator come with a clear license for online use in videos, streams, podcasts, and more.",
  section9Body2: "We design our AI music generator to avoid copying existing songs, but we cannot provide legal advice. For high-stakes campaigns, we recommend consulting your own counsel.",
  section10Heading: "AI music generator FAQ",
  faqItems: [
    { question: "What can I create with your AI music generator?", answer: "You can generate full songs, short hooks, lyrics, or pure instrumentals — all from text prompts." },
    { question: "Do I own the music I create?", answer: "You get a broad royalty-free license. For details, see our copyright and licensing section on this site." },
    { question: "Can I use AI-generated music on YouTube or TikTok?", answer: "Yes. We recommend testing on non-critical videos first and reviewing our licensing terms." },
    { question: "Do I need music production experience?", answer: "Not at all. If you can describe how you want your song to feel, the AI music generator can turn that into audio." },
    { question: "Can I start with lyrics first?", answer: "Yes. You can use our AI lyrics generator and then turn them into songs with the same AI music generator workflow." },
  ],
  ctaHeading: "Ready to create your own unique music?",
  ctaSubtitle: "Join thousands of creators who use our AI music generator.",
};

// ─────────────────────────────────────────────────────────────────────────────
// AI Music Factory — aimusicfactory.com
//
// SEO 关键词策略：以 "AI music generator for content creators" 为核心句式，
// 衍生长尾：
//   "AI music generator for YouTube videos"
//   "AI music generator for bulk content production"
//   "AI music generator for podcasters"
//   "AI music generator for multiple videos"
//   "AI music generator for TikTok and Reels"
//
// toolName = "the AI music generator" → body inline 提及天然含目标关键词
// tagline  = "AI Music Generator for Content Creators" → 出现在 H1 第二行（最高权重）
// GEO/AEO：FAQ 条目直接回答 "是否是面向内容创作者的 AI music generator" 等搜索意图
// ─────────────────────────────────────────────────────────────────────────────

const AMF_HOME_COPY: HomeCopy = {
  heroSubtitle:
    "The AI music generator for content creators who publish at scale. Describe your video, podcast, or social clip—get a royalty-free track in seconds.",
  sampleTrackDescriptions: [
    "An epic cinematic opener—the kind of track content creators generate for product launches and channel trailers.",
    "A laid-back lo-fi instrumental generated for focus videos, study content, and background playlists.",
    "A subtle background loop for talking-head videos and tutorials—produced by the AI music generator in seconds.",
    "A 15-second social clip. Use the AI music generator to batch-generate variations for Reels, Shorts, and TikTok.",
    "Gentle piano and strings for storytelling—ready for YouTube narratives and podcast intros.",
    "Bright acoustic energy for vlog openers and channel intros.",
    "Smooth neo-soul groove for lifestyle and chill content creators.",
    "Calm ambient loop for game content, tutorials, and app background.",
  ],
  section2Heading: "Everything content creators need in one AI music generator",
  section2Subtitle: "Full tracks, AI lyrics, and audio tools—the AI music generator built to keep up with your upload schedule.",
  section2Cards: [
    {
      title: "AI music generator for YouTube videos",
      copy: "Generate background music, intros, and full tracks for your YouTube channel. Build a royalty-free library fast enough for your publishing cadence.",
      href: "/ai-music-generator",
      label: "Generate for YouTube →",
    },
    {
      title: "AI music generator for lyrics and vocals",
      copy: "Write hooks and full verses in seconds. Turn them into complete vocal tracks with the same AI music generator workflow—no music background needed.",
      href: "/ai-lyrics-generator",
      label: "Try lyrics generator →",
    },
    {
      title: "AI music generator for podcasts and streams",
      copy: "Unique intros, mid-roll transitions, and ambient beds—generated on demand for your show, stream, or channel.",
      href: "/ai-music-tools",
      label: "Explore audio tools →",
    },
  ],
  section3Heading: "Hear what this AI music generator produces for content creators",
  section3Subtitle: "Preview royalty-free songs, instrumentals, and loops—every track ready to publish on YouTube, TikTok, or your podcast.",
  section4Heading: "Tools inside this AI music generator for content creators",
  section4Subtitle: "Built for creators who need music in volume. Generate instrumentals, loops, and full tracks—on demand.",
  section4Cards: [
    {
      title: "AI music generator for instrumentals",
      copy: "Generate clean instrumentals for any video background—talking-head, tutorial, vlog, or game. No composer required.",
      href: "/ai-music-tools#instrumentals",
      label: "Open instrumental generator",
    },
    {
      title: "AI music generator for loops",
      copy: "Produce looping background music for long-form videos and live streams without digging through stock libraries.",
      href: "/ai-music-tools#loops",
      label: "Explore loops tool",
    },
    {
      title: "AI music generator for social clips",
      copy: "Describe the vibe and generate multiple variations. Pick the sound that drives engagement on Reels, Shorts, and TikTok.",
      href: "/ai-music-generator",
      label: "Open AI Music Factory",
    },
  ],
  section5Heading: "The AI music generator built for your upload schedule",
  section5Body1:
    "Publishing daily or weekly takes a constant stream of fresh, royalty-free music. AI Music Factory is the AI music generator for content creators who cannot slow down for sound—describe what you need and get a finished track in seconds.",
  section5Body2:
    "Stop searching stock libraries. The AI music generator behind AI Music Factory produces unique audio matched to your content—one track or a library's worth, on demand.",
  section6Heading: "How this AI music generator works for content creators",
  section6Steps: [
    {
      step: "1. Describe your content",
      text: "Tell the AI music generator the genre, mood, and energy level. Add lyrics or keep it instrumental—your call.",
      img: "/images/home/how-1-describe.webp",
      alt: "Person typing on laptop, thinking",
    },
    {
      step: "2. Generate one or many tracks",
      text: "The AI music generator builds unique audio in seconds. Run multiple prompts in parallel to stock your channel music library.",
      img: "/images/home/how-2-ai-compose.webp",
      alt: "Hands on keyboard with sound waves",
    },
    {
      step: "3. Export and publish anywhere",
      text: "Download royalty-free tracks ready for YouTube, TikTok, podcasts, or any platform. No copyright claims, no per-video fees.",
      img: "/images/home/how-3-export.webp",
      alt: "Creator with headphones exporting",
    },
  ],
  section6FooterCta: "Start using the AI music generator",
  section7Heading: "How content creators use this AI music generator",
  section8Heading: "Who this AI music generator for content creators is built for",
  section8Subtitle: "The AI music generator for every type of creator—from solo YouTubers to podcast networks and social media agencies.",
  section8ListItems: [
    "YouTube creators who need fresh background music that fits every video—without copyright claims.",
    "Short-form editors who generate multiple clip variations daily for Reels, Shorts, and TikTok.",
    "Podcast hosts who want unique intros, transitions, and ad beds without hiring a composer.",
    "Twitch and YouTube live streamers who need ambient loops and energy tracks on demand.",
    "Indie game developers using the AI music generator for level themes and ambient soundscapes.",
    "Social media agencies managing multiple channels and needing music at scale.",
  ],
  section9Heading: "Licensing for content creators using this AI music generator",
  section9Body1:
    "Every track this AI music generator produces comes with a clear royalty-free license—ready for YouTube, TikTok, Instagram, podcasts, and commercial use.",
  section9Body2:
    "The AI music generator is designed to produce original music, not copies. For high-stakes campaigns, review our full licensing terms or consult your own counsel.",
  section10Heading: "AI music generator for content creators — FAQ",
  faqItems: [
    {
      question: "Is AI Music Factory an AI music generator for content creators?",
      answer:
        "Yes. AI Music Factory is an AI music generator built specifically for content creators who publish at scale—YouTubers, podcasters, TikTok creators, and social media teams. Generate royalty-free songs, instrumentals, and loops from text prompts, one track or many.",
    },
    {
      question: "Can I use this AI music generator to produce music for multiple videos at once?",
      answer:
        "Yes. You can run multiple prompts and generate several tracks in parallel. AI Music Factory is designed as an AI music generator for bulk content production—build your music library as fast as you publish.",
    },
    {
      question: "Is the music from this AI music generator royalty-free for YouTube and TikTok?",
      answer:
        "Yes. All tracks are royalty-free for YouTube, TikTok, Instagram, podcasts, and commercial use. No copyright claims, no per-video fees—publish everywhere your content lives.",
    },
    {
      question: "Do I need music experience to use this AI music generator?",
      answer:
        "Not at all. Describe the vibe, genre, and mood—the AI music generator produces a finished, ready-to-publish track. No DAW, no plugins, no production background needed.",
    },
    {
      question: "Can this AI music generator also create lyrics and full songs with vocals?",
      answer:
        "Yes. Use the AI lyrics generator to write hooks and verses, then turn them into complete vocal tracks with the same AI music generator workflow. Full songs or pure instrumentals—your choice.",
    },
  ],
  ctaHeading: "The AI music generator your channel has been missing",
  ctaSubtitle: "Join thousands of content creators generating music in bulk with AI Music Factory.",
};

// ─────────────────────────────────────────────────────────────────────────────
// Default config (TAMG)
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_SITE_URL =
  (typeof process !== "undefined" && process.env.NEXT_PUBLIC_SITE_URL) ||
  "https://theaimusicgenerator.com";

const DEFAULT_CONFIG: SiteBrandConfig = {
  siteUrl: DEFAULT_SITE_URL,
  siteName: "The AI Music Generator",
  shortName: "The AI Music Generator",
  tagline: "for Modern Creators",
  copyrightName: "TheAIMusicGenerator.com",
  titleTemplate: "%s | The AI Music Generator",
  defaultTitle: "The free AI Music Generator for Creators | Royalty-Free",
  defaultDescription:
    "Turn text into songs and instrumentals in seconds. Free AI music generator and lyrics tool for creators, filmmakers & YouTubers. No copyright strikes—try free.",
  ogImageAlt: "The AI Music Generator – Create royalty-free music with AI",
  toolName: "AI music generator",
  home: TAMG_HOME_COPY,
};

// ─────────────────────────────────────────────────────────────────────────────
// Host → config overrides table
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// AMF 子页面元数据
// 核心策略：每个页面标题以 "AI music generator for [use case]" 句式强化关键词
// ─────────────────────────────────────────────────────────────────────────────

const AMF_PAGES_META: Partial<Record<string, PageMeta>> = {
  "/ai-music-generator": {
    title: "AI Music Generator for Content Creators | Bulk Music Production – AI Music Factory",
    description:
      "The AI music generator for content creators. Generate royalty-free songs, instrumentals, and loops in bulk for YouTube, TikTok, and podcasts. Try free.",
  },
  "/ai-lyrics-generator": {
    title: "AI Lyrics Generator for Content Creators | Write Songs Fast – AI Music Factory",
    description:
      "Write hooks, verses, and full song lyrics in seconds with the AI music generator for content creators. Turn lyrics into royalty-free tracks instantly.",
  },
  "/ai-lyrics-to-music-generator": {
    title: "AI Lyrics to Music Generator for Content Creators | AI Music Factory",
    description:
      "Turn your lyrics into royalty-free songs with the AI music generator for content creators. Perfect for YouTube, TikTok, and podcast music.",
  },
  "/ai-rap-lyrics-generator": {
    title: "AI Rap Lyrics Generator for Content Creators | AI Music Factory",
    description:
      "Generate rap lyrics and hip-hop beats for your content with the AI music generator for content creators. Royalty-free, ready to publish.",
  },
  "/text-to-music": {
    title: "Text to Music Generator for Content Creators | AI Music Factory",
    description:
      "Type your idea and get a royalty-free track. The AI music generator for content creators—turn text into songs for YouTube, TikTok, and podcasts.",
  },
  "/ai-music-tools": {
    title: "AI Music Tools for Content Creators | Instrumentals & Loops – AI Music Factory",
    description:
      "A full suite of AI music tools for content creators. Generate instrumentals, background loops, and full tracks for YouTube, TikTok, and podcasts.",
  },
  "/ai-music-video-generator": {
    title: "AI Music Video Generator for Content Creators | AI Music Factory",
    description:
      "Generate music videos for your content with the AI music generator for content creators. Royalty-free video and audio, ready for YouTube.",
  },
  "/ai-sheet-music-generator": {
    title: "AI Sheet Music Generator | Audio to Notation – AI Music Factory",
    description:
      "Turn AI-generated audio into sheet music and MIDI. The notation tool inside AI Music Factory—the AI music generator for content creators.",
  },
  "/ai-country-music-generator": {
    title: "AI Country Music Generator for Content Creators | AI Music Factory",
    description:
      "Generate royalty-free country music for your videos and podcasts. The AI music generator for content creators—authentic Americana and Southern sound.",
  },
  "/ai-blues-music-generator": {
    title: "AI Blues Music Generator for Content Creators | AI Music Factory",
    description:
      "Generate authentic blues music for your content. The AI music generator for content creators—12-bar, Delta, and soul blues, royalty-free.",
  },
  "/free-ai-lofi-generator": {
    title: "Free AI Lofi Generator for Content Creators | Study & Chill Music – AI Music Factory",
    description:
      "Generate lofi beats for YouTube study videos, background music, and streams. The AI music generator for content creators—royalty-free, no login needed.",
  },
  "/for-youtube-creators": {
    title: "AI Music Generator for YouTube Creators | Royalty-Free Music – AI Music Factory",
    description:
      "The AI music generator for YouTube creators. Generate background music, intros, and full tracks for your channel—100% royalty-free, no copyright claims.",
  },
  "/pricing": {
    title: "Pricing | AI Music Generator for Content Creators – AI Music Factory",
    description:
      "Plans for content creators who need music at scale. Start free, upgrade for bulk production and full commercial use.",
  },
  "/resources": {
    title: "AI Music Resources for Content Creators | Guides & Tips – AI Music Factory",
    description:
      "Guides on AI music licensing, YouTube requirements, and how to use the AI music generator for content creators. Free resources.",
  },
  "/legal": {
    title: "Legal | AI Music Factory",
    description:
      "Privacy Policy, Terms of Service, and Content License for AI Music Factory. User rights, data use, and royalty-free music license terms.",
  },
  "/privacy": {
    title: "Privacy Policy | AI Music Factory",
    description:
      "Privacy Policy for AI Music Factory: how we collect, use, and protect your information. Data and cookie practices for our AI music generator service.",
  },
  "/terms": {
    title: "Terms of Service | AI Music Factory",
    description:
      "Terms of Service for AI Music Factory: user accounts, subscriptions, refunds, and legal terms. Read before using the AI music generator for content creators.",
  },
  "/license": {
    title: "Content License | Royalty-Free & Commercial Use – AI Music Factory",
    description:
      "Content License for AI Music Factory: royalty-free and commercial use rights for music produced by the AI music generator for content creators.",
  },
};

const AMF_BRAND: Partial<SiteBrandConfig> = {
  siteUrl: "https://aimusicfactory.com",
  siteName: "AI Music Factory",
  shortName: "AI Music Factory",
  // tagline 直接出现在 H1 第二行，是页面权重最高的位置——用作核心 SEO 关键词
  tagline: "AI Music Generator for Content Creators",
  copyrightName: "AIMusicFactory.com",
  titleTemplate: "%s | AI Music Factory",
  // defaultTitle：目标关键词 + 核心差异化修饰词（bulk/批量），控制在 60 字符内
  defaultTitle: "AI Music Generator for Content Creators | Bulk Music – AI Music Factory",
  defaultDescription:
    "The AI music generator for content creators who publish at scale. Generate royalty-free songs, instrumentals, and loops for YouTube, TikTok, and podcasts—in bulk. Try free.",
  ogImageAlt: "AI Music Factory – AI Music Generator for Content Creators",
  // toolName 用于 body inline 提及："paste your prompt into the AI music generator"
  // → 每次 inline 出现都自然包含核心关键词
  toolName: "the AI music generator",
  home: AMF_HOME_COPY,
  pagesMeta: AMF_PAGES_META,
};

/** 按 host（不含端口，小写）匹配的配置表；新增域名在此添加 */
const BRAND_BY_HOST: Record<string, Partial<SiteBrandConfig>> = {
  "theaimusicgenerator.com": {},
  "www.theaimusicgenerator.com": {},
  "aimusicfactory.com": AMF_BRAND,
  "www.aimusicfactory.com": { ...AMF_BRAND, siteUrl: "https://aimusicfactory.com" },
};

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function normalizeHost(host: string | null | undefined): string | null {
  if (!host || typeof host !== "string") return null;
  return host.split(":")[0].toLowerCase();
}

/**
 * 根据当前 host 返回站点文案。
 * - 服务端：传入 headers().get("host")。
 * - 静态构建：传入 null，内部用 NEXT_PUBLIC_SITE_URL 的 host 匹配。
 */
export function getSiteConfig(host: string | null | undefined): SiteBrandConfig {
  const effectiveHost =
    normalizeHost(host) ||
    (typeof process !== "undefined" && process.env.NEXT_PUBLIC_SITE_URL
      ? normalizeHost(new URL(process.env.NEXT_PUBLIC_SITE_URL).host)
      : null) ||
    "theaimusicgenerator.com";

  const overrides = BRAND_BY_HOST[effectiveHost];
  const baseUrl =
    overrides?.siteUrl ||
    (effectiveHost ? `https://${effectiveHost}` : DEFAULT_SITE_URL);
  const base = { ...DEFAULT_CONFIG, siteUrl: baseUrl };

  if (!overrides) return base;
  return { ...base, ...overrides };
}

/**
 * 服务端用：从请求头取 host 并返回站点配置。
 * 静态导出时无 headers，会退化为用 NEXT_PUBLIC_SITE_URL 的 host。
 */
export async function getServerSiteConfig(): Promise<SiteBrandConfig> {
  try {
    const { headers } = await import("next/headers");
    const h = await headers();
    const host = h.get("host");
    return getSiteConfig(host);
  } catch {
    return getSiteConfig(null);
  }
}

/**
 * 返回子页面的 title 和 description。
 * 优先使用 config.pagesMeta[route]（按域名覆盖），无覆盖时使用 defaults。
 * 在各子页面的 generateMetadata() 中调用以实现多域名元数据差异化。
 *
 * 用法：
 *   const { title, description } = getSubPageMeta(config, "/ai-music-generator", {
 *     title: "Free AI Music Generator | ...",
 *     description: "...",
 *   });
 */
export function getSubPageMeta(
  config: SiteBrandConfig,
  route: string,
  defaults: PageMeta
): PageMeta {
  const override = config.pagesMeta?.[route];
  return {
    title: override?.title ?? defaults.title,
    description: override?.description ?? defaults.description,
  };
}
